user_dashboard:
    path:     /character
    defaults: { _controller: houseBundle:Default:character }

user_map:
    path:     /map
    defaults: { _controller: houseBundle:Default:map }

user_change_map:
    path:     /change/map/{map}
    defaults: { _controller: houseBundle:Default:changeMap }

user_locale_map:
    path:     /locale/map
    defaults: { _controller: houseBundle:Default:localeMap }

user_messagerie:
    path:     /messagerie
    defaults: { _controller: houseBundle:Messagerie:index }

user_new_msg:
    path:     /messagerie/new
    defaults: { _controller: houseBundle:Messagerie:newMsg }

user_delete_msg:
    path:     /messagerie/delete
    defaults: { _controller: houseBundle:Messagerie:deleteMsg }