house:
    resource: "@houseBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:     /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_register:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }

user_choice_house:
    path:     /user/register/houses
    defaults: { _controller: AppBundle:Registration:choice }

user_choice_house_confirmed:
    path:     /user/register/houses/select/{house}
    defaults: { _controller: AppBundle:Registration:choiceconfirmed }

user_confirmed:
    path:     /user/confirmed
    defaults: { _controller: AppBundle:Registration:confirmed }